from sqlalchemy import create_engine, Column, Integer, String, ForeignKey, Enum, Date, Float, JSON, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

db_url = 'sqlite:///datalake.sqlite'
engine = create_engine(db_url, echo=True)

Base = declarative_base()

class League(Base):
    __tablename__ = 'leagues'

    league_id = Column(Integer, primary_key=True, autoincrement=False)
    slug = Column(String(100))
    name = Column(String(100))
    region = Column(String(100))

    tournaments = relationship('Tournament', back_populates='league')
    
class Tournament(Base):
    __tablename__ = 'tournaments'
    
    tournament_id = Column(Integer, primary_key=True, autoincrement=False)
    slug = Column(String(100))
    start_date = Column(Date)
    league_id = Column(Integer, ForeignKey('leagues.league_id'))  
    
    league = relationship('League', back_populates='tournaments')
    
class Match(Base):
    __tablename__ = 'matches'
    
    match_id = Column(Integer, primary_key=True, autoincrement=False)
    start_time = Column(DateTime)
    tournament_id = Column(Integer, ForeignKey('tournaments.tournament_id'))  # Corrected this line
    strategy = Column(String)    
    name_team0 = Column(String)
    name_team1 = Column(String)
    result_team0 = Column(Integer)
    result_team1 = Column(Integer)
    
    # One-to-many relationship: Match can have multiple Games
    games = relationship("Game", back_populates="match")

class Game(Base): 
    __tablename__ = 'games'

    game_id = Column(Integer, primary_key=True, autoincrement=False)
    
    match_id = Column(Integer, ForeignKey('matches.match_id'))
    frames = relationship("Frame", back_populates="game")
    frames_two = relationship("FrameTwo", back_populates="game")
    match = relationship("Match", back_populates="games")

class Frame(Base):
    __tablename__ = 'frames'
    
    id = Column(Integer, primary_key=True)
    game_time = Column(DateTime)
    
    # Many-to-one relationship: Frame belongs to one Game
    game_id = Column(Integer, ForeignKey('games.game_id'))
    
    # Define a back reference to access the parent Game from Frame
    game = relationship("Game", back_populates="frames")    
    
    # Define columns for each participant
    participant1_level = Column(Integer)
    participant1_kills = Column(Integer)
    participant1_deaths = Column(Integer)
    participant1_assists = Column(Integer)
    participant1_totalGoldEarned = Column(Integer)
    participant1_creepScore = Column(Integer)
    participant1_killParticipation = Column(Float)
    participant1_championDamageShare = Column(Float)
    participant1_wardsPlaced = Column(Integer)
    participant1_wardsDestroyed = Column(Integer)
    participant1_attackDamage = Column(Integer)
    participant1_abilityPower = Column(Integer)
    participant1_criticalChance = Column(Float)
    participant1_attackSpeed = Column(Integer)
    participant1_lifeSteal = Column(Float)
    participant1_armor = Column(Integer)
    participant1_magicResistance = Column(Integer)
    participant1_tenacity = Column(Float)
    participant1_items = Column(JSON)
    participant1_perkMetadata = Column(JSON)
    
    participant2_level = Column(Integer)
    participant2_kills = Column(Integer)
    participant2_deaths = Column(Integer)
    participant2_assists = Column(Integer)
    participant2_totalGoldEarned = Column(Integer)
    participant2_creepScore = Column(Integer)
    participant2_killParticipation = Column(Float)
    participant2_championDamageShare = Column(Float)
    participant2_wardsPlaced = Column(Integer)
    participant2_wardsDestroyed = Column(Integer)
    participant2_attackDamage = Column(Integer)
    participant2_abilityPower = Column(Integer)
    participant2_criticalChance = Column(Float)
    participant2_attackSpeed = Column(Integer)
    participant2_lifeSteal = Column(Float)
    participant2_armor = Column(Integer)
    participant2_magicResistance = Column(Integer)
    participant2_tenacity = Column(Float)
    participant2_items = Column(JSON)
    participant2_perkMetadata = Column(JSON)
    
    participant3_level = Column(Integer)
    participant3_kills = Column(Integer)
    participant3_deaths = Column(Integer)
    participant3_assists = Column(Integer)
    participant3_totalGoldEarned = Column(Integer)
    participant3_creepScore = Column(Integer)
    participant3_killParticipation = Column(Float)
    participant3_championDamageShare = Column(Float)
    participant3_wardsPlaced = Column(Integer)
    participant3_wardsDestroyed = Column(Integer)
    participant3_attackDamage = Column(Integer)
    participant3_abilityPower = Column(Integer)
    participant3_criticalChance = Column(Float)
    participant3_attackSpeed = Column(Integer)
    participant3_lifeSteal = Column(Float)
    participant3_armor = Column(Integer)
    participant3_magicResistance = Column(Integer)
    participant3_tenacity = Column(Float)
    participant3_items = Column(JSON)
    participant3_perkMetadata = Column(JSON)
    
    participant4_level = Column(Integer)
    participant4_kills = Column(Integer)
    participant4_deaths = Column(Integer)
    participant4_assists = Column(Integer)
    participant4_totalGoldEarned = Column(Integer)
    participant4_creepScore = Column(Integer)
    participant4_killParticipation = Column(Float)
    participant4_championDamageShare = Column(Float)
    participant4_wardsPlaced = Column(Integer)
    participant4_wardsDestroyed = Column(Integer)
    participant4_attackDamage = Column(Integer)
    participant4_abilityPower = Column(Integer)
    participant4_criticalChance = Column(Float)
    participant4_attackSpeed = Column(Integer)
    participant4_lifeSteal = Column(Float)
    participant4_armor = Column(Integer)
    participant4_magicResistance = Column(Integer)
    participant4_tenacity = Column(Float)
    participant4_items = Column(JSON)
    participant4_perkMetadata = Column(JSON)
    
    participant5_level = Column(Integer)
    participant5_kills = Column(Integer)
    participant5_deaths = Column(Integer)
    participant5_assists = Column(Integer)
    participant5_totalGoldEarned = Column(Integer)
    participant5_creepScore = Column(Integer)
    participant5_killParticipation = Column(Float)
    participant5_championDamageShare = Column(Float)
    participant5_wardsPlaced = Column(Integer)
    participant5_wardsDestroyed = Column(Integer)
    participant5_attackDamage = Column(Integer)
    participant5_abilityPower = Column(Integer)
    participant5_criticalChance = Column(Float)
    participant5_attackSpeed = Column(Integer)
    participant5_lifeSteal = Column(Float)
    participant5_armor = Column(Integer)
    participant5_magicResistance = Column(Integer)
    participant5_tenacity = Column(Float)
    participant5_items = Column(JSON)
    participant5_perkMetadata = Column(JSON)
    
    participant6_level = Column(Integer)
    participant6_kills = Column(Integer)
    participant6_deaths = Column(Integer)
    participant6_assists = Column(Integer)
    participant6_totalGoldEarned = Column(Integer)
    participant6_creepScore = Column(Integer)
    participant6_killParticipation = Column(Float)
    participant6_championDamageShare = Column(Float)
    participant6_wardsPlaced = Column(Integer)
    participant6_wardsDestroyed = Column(Integer)
    participant6_attackDamage = Column(Integer)
    participant6_abilityPower = Column(Integer)
    participant6_criticalChance = Column(Float)
    participant6_attackSpeed = Column(Integer)
    participant6_lifeSteal = Column(Float)
    participant6_armor = Column(Integer)
    participant6_magicResistance = Column(Integer)
    participant6_tenacity = Column(Float)
    participant6_items = Column(JSON)
    participant6_perkMetadata = Column(JSON)
    
    participant7_level = Column(Integer)
    participant7_kills = Column(Integer)
    participant7_deaths = Column(Integer)
    participant7_assists = Column(Integer)
    participant7_totalGoldEarned = Column(Integer)
    participant7_creepScore = Column(Integer)
    participant7_killParticipation = Column(Float)
    participant7_championDamageShare = Column(Float)
    participant7_wardsPlaced = Column(Integer)
    participant7_wardsDestroyed = Column(Integer)
    participant7_attackDamage = Column(Integer)
    participant7_abilityPower = Column(Integer)
    participant7_criticalChance = Column(Float)
    participant7_attackSpeed = Column(Integer)
    participant7_lifeSteal = Column(Float)
    participant7_armor = Column(Integer)
    participant7_magicResistance = Column(Integer)
    participant7_tenacity = Column(Float)
    participant7_items = Column(JSON)
    participant7_perkMetadata = Column(JSON)
    
    participant8_level = Column(Integer)
    participant8_kills = Column(Integer)
    participant8_deaths = Column(Integer)
    participant8_assists = Column(Integer)
    participant8_totalGoldEarned = Column(Integer)
    participant8_creepScore = Column(Integer)
    participant8_killParticipation = Column(Float)
    participant8_championDamageShare = Column(Float)
    participant8_wardsPlaced = Column(Integer)
    participant8_wardsDestroyed = Column(Integer)
    participant8_attackDamage = Column(Integer)
    participant8_abilityPower = Column(Integer)
    participant8_criticalChance = Column(Float)
    participant8_attackSpeed = Column(Integer)
    participant8_lifeSteal = Column(Float)
    participant8_armor = Column(Integer)
    participant8_magicResistance = Column(Integer)
    participant8_tenacity = Column(Float)
    participant8_items = Column(JSON)
    participant8_perkMetadata = Column(JSON)
    
    participant9_level = Column(Integer)
    participant9_kills = Column(Integer)
    participant9_deaths = Column(Integer)
    participant9_assists = Column(Integer)
    participant9_totalGoldEarned = Column(Integer)
    participant9_creepScore = Column(Integer)
    participant9_killParticipation = Column(Float)
    participant9_championDamageShare = Column(Float)
    participant9_wardsPlaced = Column(Integer)
    participant9_wardsDestroyed = Column(Integer)
    participant9_attackDamage = Column(Integer)
    participant9_abilityPower = Column(Integer)
    participant9_criticalChance = Column(Float)
    participant9_attackSpeed = Column(Integer)
    participant9_lifeSteal = Column(Float)
    participant9_armor = Column(Integer)
    participant9_magicResistance = Column(Integer)
    participant9_tenacity = Column(Float)
    participant9_items = Column(JSON)
    participant9_perkMetadata = Column(JSON)
    
    participant10_level = Column(Integer)
    participant10_kills = Column(Integer)
    participant10_deaths = Column(Integer)
    participant10_assists = Column(Integer)
    participant10_totalGoldEarned = Column(Integer)
    participant10_creepScore = Column(Integer)
    participant10_killParticipation = Column(Float)
    participant10_championDamageShare = Column(Float)
    participant10_wardsPlaced = Column(Integer)
    participant10_wardsDestroyed = Column(Integer)
    participant10_attackDamage = Column(Integer)
    participant10_abilityPower = Column(Integer)
    participant10_criticalChance = Column(Float)
    participant10_attackSpeed = Column(Integer)
    participant10_lifeSteal = Column(Float)
    participant10_armor = Column(Integer)
    participant10_magicResistance = Column(Integer)
    participant10_tenacity = Column(Float)
    participant10_items = Column(JSON)
    participant10_perkMetadata = Column(JSON)
    
class FrameTwo(Base):
    __tablename__ = 'frames_two'
    
    id = Column(Integer, primary_key=True)
    game_time = Column(DateTime)
    
    # Many-to-one relationship: Frame belongs to one Game
    game_id = Column(Integer, ForeignKey('games.game_id'))
    
    # Define a back reference to access the parent Game from Frame
    game = relationship("Game", back_populates="frames_two")    
    
    blueTeam_totalGold = Column(Integer)
    blueTeam_inhibitors = Column(Integer)
    blueTeam_towers = Column(Integer)
    blueTeam_barons = Column(Integer)
    blueTeam_totalKills = Column(Integer)
    blueTeam_dragons = Column(JSON)  
     
    redTeam_totalGold = Column(Integer)
    redTeam_inhibitors = Column(Integer)
    redTeam_towers = Column(Integer)
    redTeam_barons = Column(Integer)
    redTeam_totalKills = Column(Integer)
    redTeam_dragons = Column(JSON)
    
    participant1_totalGold = Column(Integer)
    participant1_level = Column(Integer)
    participant1_kills = Column(Integer)
    participant1_deaths = Column(Integer)
    participant1_assists  = Column(Integer)
    participant1_creepScore  = Column(Integer)
    participant1_currentHealth = Column(Integer)
    participant1_maxHealth  = Column(Integer)
    
    participant2_totalGold = Column(Integer)
    participant2_level = Column(Integer)
    participant2_kills = Column(Integer)
    participant2_deaths = Column(Integer)
    participant2_assists  = Column(Integer)
    participant2_creepScore  = Column(Integer)
    participant2_currentHealth = Column(Integer)
    participant2_maxHealth  = Column(Integer)
    
    participant3_totalGold = Column(Integer)
    participant3_level = Column(Integer)
    participant3_kills = Column(Integer)
    participant3_deaths = Column(Integer)
    participant3_assists  = Column(Integer)
    participant3_creepScore  = Column(Integer)
    participant3_currentHealth = Column(Integer)
    participant3_maxHealth  = Column(Integer)
    
    participant4_totalGold = Column(Integer)
    participant4_level = Column(Integer)
    participant4_kills = Column(Integer)
    participant4_deaths = Column(Integer)
    participant4_assists  = Column(Integer)
    participant4_creepScore  = Column(Integer)
    participant4_currentHealth = Column(Integer)
    participant4_maxHealth  = Column(Integer)
    
    participant5_totalGold = Column(Integer)
    participant5_level = Column(Integer)
    participant5_kills = Column(Integer)
    participant5_deaths = Column(Integer)
    participant5_assists  = Column(Integer)
    participant5_creepScore  = Column(Integer)
    participant5_currentHealth = Column(Integer)
    participant5_maxHealth  = Column(Integer)
    
    participant6_totalGold = Column(Integer)
    participant6_level = Column(Integer)
    participant6_kills = Column(Integer)
    participant6_deaths = Column(Integer)
    participant6_assists  = Column(Integer)
    participant6_creepScore  = Column(Integer)
    participant6_currentHealth = Column(Integer)
    participant6_maxHealth  = Column(Integer)
    
    participant7_totalGold = Column(Integer)
    participant7_level = Column(Integer)
    participant7_kills = Column(Integer)
    participant7_deaths = Column(Integer)
    participant7_assists  = Column(Integer)
    participant7_creepScore  = Column(Integer)
    participant7_currentHealth = Column(Integer)
    participant7_maxHealth  = Column(Integer)
    
    participant8_totalGold = Column(Integer)
    participant8_level = Column(Integer)
    participant8_kills = Column(Integer)
    participant8_deaths = Column(Integer)
    participant8_assists  = Column(Integer)
    participant8_creepScore  = Column(Integer)
    participant8_currentHealth = Column(Integer)
    participant8_maxHealth  = Column(Integer)
    
    participant9_totalGold = Column(Integer)
    participant9_level = Column(Integer)
    participant9_kills = Column(Integer)
    participant9_deaths = Column(Integer)
    participant9_assists  = Column(Integer)
    participant9_creepScore  = Column(Integer)
    participant9_currentHealth = Column(Integer)
    participant9_maxHealth  = Column(Integer)
    
    participant10_totalGold = Column(Integer)
    participant10_level = Column(Integer)
    participant10_kills = Column(Integer)
    participant10_deaths = Column(Integer)
    participant10_assists  = Column(Integer)
    participant10_creepScore  = Column(Integer)
    participant10_currentHealth = Column(Integer)
    participant10_maxHealth  = Column(Integer)
    
    
    
Base.metadata.create_all(engine)


Session = sessionmaker(bind=engine)